name: Backend CI

on:
  push:
    branches:
      - main # Trigger CI on pushes to the main branch

jobs:
  test:
    name: Run Tests
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Node.js with npm caching
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      # Stop running apps
      - run: pm2 stop all || true

      # Create .env before installing/running
      - name: Create .env file
        working-directory: ./backend
        run: |
          touch .env
          echo "MONGO_URI=${{ secrets.MONGO_URI }}" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "PORT=${{ secrets.PORT }}" >> .env

      # Install backend dependencies
      - name: Install Backend Dependencies
        working-directory: ./backend
        run: npm ci --prefer-offline --no-audit

      # Cache frontend dependencies
      - name: Cache Frontend Dependencies
        uses: actions/cache@v3
        with:
          path: frontend/node_modules
          key: frontend-node-modules-${{ hashFiles('frontend/package-lock.json') }}
          restore-keys: frontend-node-modules-

      # Install frontend dependencies
      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: npm ci --prefer-offline --no-audit --verbose
        timeout-minutes: 15 # Fail fast if stuck

      # Build Frontend
      - name: Build Frontend
        working-directory: ./frontend
        run: NODE_OPTIONS=--max-old-space-size=4096 npm run build

      # Run backend tests
      - name: Run Backend Tests
        working-directory: ./backend
        run: npm test

      # Restart backend with pm2
      - name: Restart PM2
        run: |
          pm2 startOrRestart ecosystem.config.js || pm2 restart all
